services:
  raidtrack-bot:
    image: ghcr.io/macieq1989/raidtrack-discord-bot:latest
    container_name: raidtrack-bot
    restart: unless-stopped
    env_file: [.env]
    volumes:
      - ./data:/app/data
      - /mnt/wow-sv:/data/sv:ro
    ports:
      - "19000:18080"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:18080/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 3s
      retries: 3 
    environment:
      - SV_FILE=/data/sv/RaidTrack.lua
      - SV_EXPORT_KEY=RaidTrackExport
      - ASSET_ICON_DIR=/app/assets/icons
      - ICON_OFFLINE_ONLY=true
