name: Build & Push Docker image
on:
  push:
    branches: ['main']
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          IMAGE=ghcr.io/macieq1989/raidtrack-discord-bot
          docker build -t $IMAGE:latest .
      - name: Push
        run: |
          IMAGE=ghcr.io/macieq1989/raidtrack-discord-bot
          docker push $IMAGE:latest
