name: Build & Push Docker image

on:
  push:
    tags: ['v*.*.*']
    branches: ['main']

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository }}:latest -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          fi
